
pool:
  vmImage: ubuntu-latest

steps:

- script: |
    echo Hola mundo
  displayName: 'Hola Mundo'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonar-azure'
    organization: 'christhian45'
    scannerMode: 'Other'
    projectKey: 'Christhian45_springpet-clinic'
    projectName: 'springpet-clinic'
  displayName: 'SonarCloud Prepare'

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'sonarqube'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.5.0.2730'
    spotBugsAnalysis: false

